?start	: expression
		| query

query	: expression "?"

?expression	: operation

?operation	: binary
			| unary

?binary	: weak_disjunction
		| l_strong_disjunction
		| conjunction
		| l_strong_conjunction
		| g_implication
		| l_implication
		| j_implication
		| k_implication
		| g_bi_implication
		| l_bi_implication
		| j_bi_implication
		| k_bi_implication

?unary	: weak_negation
		| post_negation
		| strong_negation
		| mosil_nabla_operator
		| baaz_delta_operator
		| doubtful_operator
		| consistency
		| parentheses
		| variable
		| value

weak_negation			: "\\overline{" expression "}"
post_negation			: "!" expression
strong_negation			: "\\lnot" unary
mosil_nabla_operator	: "\\nabla" unary
baaz_delta_operator		: "\\Delta" unary
doubtful_operator		: "I" unary
consistency				: "\\circ" unary
?parentheses			: "\\left(" expression "\\right)"
variable				: VARIABLE
value					: VALUE

weak_disjunction		: expression "\\lor" unary
l_strong_disjunction	: expression "\\oplus" unary
conjunction				: expression "\\land" unary
l_strong_conjunction	: expression "\\otimes" unary
g_implication			: expression "\\xrightarrow[G]{}" unary
l_implication			: expression "\\xrightarrow[L]{}" unary
j_implication			: expression "\\xrightarrow[J]{}" unary
k_implication			: expression "\\xrightarrow[K]{}" unary
g_bi_implication		: expression "\\xleftrightarrow[G]{}" unary
l_bi_implication		: expression "\\xleftrightarrow[L]{}" unary
j_bi_implication		: expression "\\xleftrightarrow[J]{}" unary
k_bi_implication		: expression "\\xleftrightarrow[K]{}" unary

VARIABLE	: /[a-z]/

VALUE	: "0"
		| "\\frac12" | "\\frac{1}{2}"
		| "1"

%import common.WS

%ignore WS
