?start	: expression

?expression	: operation

?operation	: binary
			| unary

?binary	: disjunction
		| conjunction
		| implication

?unary	: negation
		| parentheses
		| value

negation		: "\\sim" unary
?parentheses	: "\\left(" expression "\\right)"
value			: VALUE

disjunction	: expression "\\lor" unary
conjunction	: expression "\\land" unary
implication	: expression "\\rightarrow" unary

VALUE	: "0"
		| "\\frac12" | "\\frac{1}{2}"
		| "1"

%import common.WS

%ignore WS
